### PR TITLE
[docker:android-base] Support JDK-11 and build-tool 31.

### PR DESCRIPTION
**Pull request by ank27**
- Update jdk 11 to support gradle bump.
- Added build tool 31.

### CODE REVIEW

**Review by kiryldz — APPROVED** [review]
I guess as CI did pass - latest CI image is already getting used so let's make it official then and merge 😉

**Review by yunikkk — APPROVED** [review]

**Comment by LukasPaczos** [comment]
This enforces Java 11 for all downstream projects which can be a change that breaks the integration, it did for [`mapbox-java`](https://github.com/mapbox/mapbox-java) which does not compile anymore (it's using `android-ndk-r21e:latest`).

What's the motivation for this change, are we ready to enforce Java 11 across all the consumers of the images? There's already the [r22 image](https://github.com/mapbox/mbgl-ci-images/blob/master/images/android-ndk-r22) that uses Java 15 and should suffice for all use-cases that require Java 11.

We might want to revert this change and make sure that all consumers can actually run against Java 11, otherwise, we could unintentionally impact a lot of projects, especially given how disrupting the switch to Java 11 can be for Android projects.

**Comment by LukasPaczos** [comment]
Linking `mapbox-java` stopgap PR until we add Java 11 support for that project - https://github.com/mapbox/mapbox-java/pull/1359.

**Comment by ank27** [comment]
@LukasPaczos this change is needed to bump the latest android Gradle in sync with upstream projects, else we get a compilation error regarding java8. It is mentioned in the internal ticket associated with this. 

But If downstream projects are using `ndk-21e:latest`, I think we can revert this in order to not break the integration.

**Comment by tobrun** [comment]
> This enforces Java 11 for all downstream projects which can be a change that breaks the integration, it did for [mapbox-java](https://github.com/mapbox/mapbox-java) which does not compile anymore (it's using android-ndk-r21e:latest).

We should avoid using `latest` and always pin to a fixed sha. It's not like it our CI images are semver versioned and that bumping jdk to 11 was a major breaking change.. 

>What's the motivation for this change, are we ready to enforce Java 11 across all the consumers of the images? There's already the [r22 image](https://github.com/mapbox/mbgl-ci-images/blob/master/images/android-ndk-r22) that uses Java 15 and should suffice for all use-cases that require Java 11.

Any reason why we should adopt ndk-22? There hasn't been a decision at Maps to adopt it. I don't think it's a valid workaround for this situation.

**Comment by LukasPaczos** [comment]
> We should avoid using latest and always pin to a fixed sha. It's not like it our CI images are semver versioned and that bumping jdk to 11 was a major breaking change..

Pinning to a specific image is fine, but if we wanted to enhance that image with a "non-breaking" change (like adding new platform tools) after the "breaking" change like bumping Java version has been introduced, a downstream project wouldn't be able to just use the new platform tools without also having to adopt Java 11. 

I any case, even if we're not versioning the images, knowing how impactful changes in images can be (making/breaking downstream pipelines at an instant), we should setup a communication/review process to make sure we're not unintentionally impacting other projects. Possibly something as simple as making all Android teams code owners for the Android images might suffice.

@tobrun is this something that we could add to the CoE agenda?

Side note - a lot of projects that do use images from this project do not use NDK at all, so maybe we should also think about branching off NDK and non-NDK images to add an alternative versioning channel where NDK is not the primary factor.

> But If downstream projects are using ndk-21e:latest, I think we can revert this in order to not break the integration.

@ank27 I'd recommend at least giving other Android teams a heads up at `#android` slack channel to see if there could be more projects impacted. If it's only `mapbox-java`, we should be fine to leave things as they are.

**Pull request merged**
